[package]
name = "toy-sqlite"
version = "0.1.0"
authors = ["phatho.pukwana@gmail.com"]
edition = "2021"


# DON'T EDIT THIS!
[dependencies]
anyhow = "1.0.59"    # error handling
itertools = "0.14.0" # useful iterator extensions
regex = "1.5.4"      # for parsing
